# Automatically move newly created issues into the "To do" column of the "User Story Status" project
# Workflow parameter documentation located here: https://github.com/marketplace/actions/github-project-automation
name: Move new issues into To do

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: User Story Status
          column: To do
          repo-token: ${{ secrets.WDD project workflow automation }}
